# Top-Level Parameters
range: 6500000                  # Range in meters
cruise_speed: 250               # Cruise speed in m/s # TODO, update as a function of mach, for consistency and ease of changes
cruise_mach: 0.85               # Cruise Mach Number
stall_speed_clean: 110          # Stall speed clean configuration in kts
stall_speed_land: 85            # Stall speed landing configuration in kts
cruise_altitude: 12100         # Cruise altitude in meters
cruise_density: 0.3059685       # Cruise density in kg/m^3
takeoff_distance: 1500 # 1500          # Takeoff distance in meters
landing_distance: 1350 # 1200          # Landing distance in meters
diversion_distance: 460000      # Diversion distance in meters
loiter_time: 7200               # Loiter time in seconds
max_eq_velocity: 207.549        # Maximum Equivalent Velocity in kts
max_load_factor: 3.3            # Maximum Load Factor
crit_mach: 0.75                 # Critical Mach Number TODO why is this a top level parameter? What? Alejandro
cruise_viscosity: 0.00004
cruise_aoa: 0.03 #placeholder value for cruise aoa in rad

# Performance Parameters
performance:
  climb_rate: 17.8                  # Climb Rate in m/s
  climb_rate_alt: 0               # Climb Rate Altitude in m
  climb_gradient_AEO: 0.04         # Climb Gradient AEO
  climb_gradient_OEI: 0.0075       # Climb Gradient OEI
  climb_gradient_AEO_alt: 0       # Climb Gradient AEO Altitude in ft
  climb_gradient_OEI_alt: 1500      # Climb Gradient OEI Altitude in ft
  delta_CD0_OEI: 0.005            # Zero-Lift Drag Coefficient Differential AEO

# Engine Parameters
engine:
  cruise_thrust_setting: 0.9      # Thrust setting for cruise
  engine_weight: 2296.521         # Engine Weight in N
  engine_max_thrust: 13340        # Engine Maximum Thrust in N
  engine_length: 1.47             # Engine Length in m
  engine_diameter: 0.53           # Engine Diameter in m
  nacelle_diameter: 0.71            # Nacelle Diameter in m
  nacelle_length: 2.2          # Nacelle Length in m
  cruise_tsfc: 0.685              # Cruise TSFC in lb/h/lbf